server:
    port: ${PORT:10000}
spring:
    application:
        name: order
    config:
        import: ${CHOST:configserver:http://127.0.0.1:8888}
resilience4j:
    retry:
        instances:
            reservation_retry:
                max-attempts: 3
                wait-duration: '100ms'
                ignore-exceptions:
                  - java.lang.IllegalArgumentException
                  - java.nio.file.AccessDeniedException
                retry-exception-predicate: com.microservices.training.msorder.integrations.MyRetryPredicate
                result-predicate: com.microservices.training.msorder.integrations.KitchenResultPredicate
    circuitbreaker:
        instances:
            reservation_cb:
                sliding-window-type: count_based
                sliding-window-size: 20
                minimum-number-of-calls: 10
                failure-rate-threshold: 30
                wait-duration-in-open-state: '5s'
                automatic-transition-from-open-to-half-open-enabled: false
                permitted-number-of-calls-in-half-open-state: 5
                max-wait-duration-in-half-open-state: '5s'
                slow-call-rate-threshold: 70
                slow-call-duration-threshold: '200ms'


