server:
    port: ${PORT:8080}
spring:
    application:
        name: apigw-order
    config:
        import: ${CHOST:configserver:http://127.0.0.1:8888}
    cloud:
        discovery:
          enabled: true
        gateway:
            enabled: true
            discovery:
                locator:
                    enabled: true
            routes:
                - id: order_route
                  uri: lb://ORDER
                  predicates:
                    - Path=/api/v1/order/**

